version: "3"

services: 
  postgres_db:
    image: postgres
    container_name: postgres_db
    environment: 
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: root
     POSTGRES_DB: brisa_test
    expose:
     - "5432"
  app: 
    build: .
    command: "npm run start"
    environment: 
     TYPEORM_HOST: postgres_db
    ports: 
     - "3333:3333"
    volumes:
     - .:/usr/app
    depends_on:
     - postgres_db
     